Repository marcosdosea/GestaoEscolar, pull requests merged in 2021-02, with the labels that each got.

#151 Views Disciplina
  Código/SiCAEWeb/SiCAEWeb.csproj
  Código/SiCAEWeb/Views/Diahora/Create.cshtml
  Código/SiCAEWeb/Views/Diahora/Delete.cshtml
  Código/SiCAEWeb/Views/Diahora/Details.cshtml
  Código/SiCAEWeb/Views/Diahora/Edit.cshtml
  Código/SiCAEWeb/Views/Diahora/Index.cshtml
  Código/SiCAEWeb/Views/Disciplina/Create.cshtml
  Código/SiCAEWeb/Views/Disciplina/Delete.cshtml
  Código/SiCAEWeb/Views/Disciplina/Details.cshtml
  Código/SiCAEWeb/Views/Disciplina/Edit.cshtml
  Código/SiCAEWeb/Views/Disciplina/Index.cshtml
  Código/SiCAEWeb/Views/Home/Index.cshtml
  Código/SiCAEWeb/Views/Shared/_Layout.cshtml
  Código/SiCAEWeb/wwwroot/css/site.css
  Código/SiCAEWeb/wwwroot/img/logo.png
Labels: Front-end

#158 Alteradas Views de Aluno
  Código/SiCAEWeb/Startup.cs
  Código/SiCAEWeb/Views/Aluno/Create.cshtml
  Código/SiCAEWeb/Views/Aluno/Delete.cshtml
  Código/SiCAEWeb/Views/Aluno/Details.cshtml
  Código/SiCAEWeb/Views/Aluno/Edit.cshtml
  Código/SiCAEWeb/Views/Aluno/Index.cshtml
  Código/SiCAEWeb/Views/Diahora/Create.cshtml
  Código/SiCAEWeb/Views/Diahora/Delete.cshtml
  Código/SiCAEWeb/Views/Diahora/Details.cshtml
  Código/SiCAEWeb/Views/Diahora/Edit.cshtml
  Código/SiCAEWeb/Views/Diahora/Index.cshtml
  Código/SiCAEWeb/Views/Disciplina/Create.cshtml
  Código/SiCAEWeb/Views/Disciplina/Delete.cshtml
  Código/SiCAEWeb/Views/Disciplina/Details.cshtml
  Código/SiCAEWeb/Views/Disciplina/Edit.cshtml
  Código/SiCAEWeb/Views/Disciplina/Index.cshtml
  Código/SiCAEWeb/Views/Home/Index.cshtml
  Código/SiCAEWeb/Views/Shared/_Layout.cshtml
  Código/SiCAEWeb/wwwroot/css/site.css
  Código/SiCAEWeb/wwwroot/img/logo.png
Labels: Front-end

#161 Alteração das Views de Escola
  Código/SiCAEWeb/Views/Escola/Create.cshtml
  Código/SiCAEWeb/Views/Escola/Delete.cshtml
  Código/SiCAEWeb/Views/Escola/Details.cshtml
  Código/SiCAEWeb/Views/Escola/Edit.cshtml
  Código/SiCAEWeb/Views/Escola/Index.cshtml
Labels: Front-end

#162 Alteração nas Views de Pessoa
  Código/SiCAEWeb/Views/Pessoa/AdicionarPessoa.cshtml
  Código/SiCAEWeb/Views/Pessoa/AlterarPessoa.cshtml
  Código/SiCAEWeb/Views/Pessoa/Index.cshtml
Labels: Front-end

#169 Adição do caso de uso 16
  Requisitos/Caso de uso - nível sistema/CSU16-Manter Avaliação.doc
Labels: documentation

#168 julia97lima#145.cont
  Código/Core/Pessoa.cs
  Código/Core/Service/IPessoaService.cs
  Código/Service/PessoaService.cs
  Código/SiCAEWeb/Controllers/PessoaController.cs
  Código/SiCAEWeb/Models/PessoaModel.cs
  Código/SiCAEWeb/Views/Pessoa/ExcluirPesoa.cshtml
  Código/SiCAEWeb/Views/Pessoa/Index.cshtml
Labels: Back-end

#177 Alteração nos index das views
  Código/SiCAEWeb/Views/Aluno/Index.cshtml
  Código/SiCAEWeb/Views/Disciplina/Index.cshtml
  Código/SiCAEWeb/Views/Escola/Index.cshtml
Labels: Front-end

#175 Implementação do menu
  Código/SiCAEWeb/Views/Aluno/Index.cshtml
  Código/SiCAEWeb/Views/Shared/_Layout.cshtml
  Código/SiCAEWeb/wwwroot/css/site.css
  Código/SiCAEWeb/wwwroot/img/logo-white.png
Labels: Front-end

#181 Alterações em tabelas do banco
  Análise de Projeto/SiCAE.mwb
  Análise de Projeto/SiCAE.mwb.bak
Labels: BD

#187 Alteração do nome do CSU03
  Requisitos/Caso de uso - nível usuário/CSU03-Manter Pessoa.doc
Labels: documentation

#195 Implementação de métodos do CSU08
  Código/Core/Service/INotificacaoService.cs
  Código/Service/NotificacaoService.cs
  Código/SiCAEWeb/Controllers/NotificacaoController.cs
  Código/SiCAEWeb/Views/Notificacao/Detalhes.cshtml
  Código/SiCAEWeb/Views/Notificacao/ExcluirNotificacao.cshtml
  Código/SiCAEWeb/Views/Notificacao/Index.cshtml
Labels: Back-end

#196 Adição do método inserir notificação
  Código/Core/Service/INotificacaoService.cs
  Código/Service/NotificacaoService.cs
  Código/SiCAEWeb/Controllers/NotificacaoController.cs
  Código/SiCAEWeb/Views/Notificacao/AdicionarNotificacao.cshtml
  Código/SiCAEWeb/Views/Notificacao/Index.cshtml
Labels: Back-end

#210 Alteração em tabelas do banco
  Análise de Projeto/SiCAE.mwb
  Análise de Projeto/SiCAE.mwb.bak
Labels: BD, Back-end

#212 Alteração da tela inicial, da tela de login e links de menu
  Código/SiCAEWeb/Areas/Identity/Pages/Account/Login.cshtml
  Código/SiCAEWeb/Views/Home/Index.cshtml
  Código/SiCAEWeb/Views/Shared/_Layout.cshtml
  Código/SiCAEWeb/Views/Shared/_LoginPartial.cshtml
Labels: Front-end
